server:
  port: 9001
spring:
  application:
    name: e-commerce-service
  datasource:
      url: jdbc:postgresql://localhost:5432/ECommerce
      username: postgres
      password: root
      driverClassName: org.postgresql.Driver
  jpa:
   database: POSTGRESQL